@startuml
title graphs

interface Graph<N> {
+ getNodes()
+ getNeighbours(root)
+ hasNode(node)
+ areNeighbors(root, neighbor)

+ DFS(start, end)
+ BFS(start, end)
}

interface WeightedGraph<N, E> {
  + getEdges(root)
  + hasEdge(root, edge)

  + djikstras(start, end, weightFunc: Function<Pair<E, N>, Double)
  + <T>djikstras(start, end, comparator, reducer: (a, b) -> T)
}

WeightedGraph -> Graph
@enduml